import type { PrevisioneUscita } from './types';

export const previsioniUsciteData: PrevisioneUscita[] = [
  {
    id: 'LNC-PU-1',
    societa: 'LNC',
    anno: 2025,
    mese: 'Dicembre',
    dataScadenza: '2025-12-31',
    descrizione: 'Commercialista - Compenso annuale',
    categoria: 'Gestione Generale',
    sottocategoria: 'Commercialista',
    importoLordo: 400.00,
    iva: 0.22,
    certezza: 'Certa',
    probabilita: 1.0,
    stato: 'Da pagare',
    fonteContratto: 'Incarico professionale',
    ricorrenza: 'Annuale',
  },
  {
    id: 'LNC-PU-2',
    societa: 'LNC',
    anno: 2025,
    mese: 'Gennaio',
    dataScadenza: '2025-01-31',
    descrizione: 'Canone Banca Online BAPR',
    categoria: 'Gestione Generale',
    sottocategoria: 'Spese Bancarie',
    importoLordo: 1.00,
    iva: 0.0,
    certezza: 'Certa',
    probabilita: 1.0,
    stato: 'Da pagare',
    fonteContratto: 'Contratto bancario',
    ricorrenza: 'Mensile',
    note: '€0.50 x 2',
  },
  {
    id: 'LNC-PU-3',
    societa: 'LNC',
    anno: 2025,
    mese: 'Febbraio',
    dataScadenza: '2025-02-28',
    descrizione: 'Canone Banca Online BAPR',
    categoria: 'Gestione Generale',
    sottocategoria: 'Spese Bancarie',
    importoLordo: 1.00,
    iva: 0.0,
    certezza: 'Certa',
    probabilita: 1.0,
    stato: 'Da pagare',
    fonteContratto: 'Contratto bancario',
    ricorrenza: 'Mensile',
    note: '€0.50 x 2',
  },
  {
    id: 'LNC-PU-4',
    societa: 'LNC',
    anno: 2025,
    mese: 'Marzo',
    dataScadenza: '2025-03-31',
    descrizione: 'Canone Banca Online BAPR',
    categoria: 'Gestione Generale',
    sottocategoria: 'Spese Bancarie',
    importoLordo: 1.00,
    iva: 0.0,
    certezza: 'Certa',
    probabilita: 1.0,
    stato: 'Pagato',
    fonteContratto: 'Contratto bancario',
    ricorrenza: 'Mensile',
    note: '€0.50 x 2',
    importoEffettivo: 1.00,
  },
  // Add more data based on the image
  {
    id: 'STG-PU-1',
    societa: 'STG',
    anno: 2025,
    mese: 'Gennaio',
    dataScadenza: '2025-01-15',
    descrizione: 'Manutenzione impianto fotovoltaico',
    categoria: 'Fornitori',
    sottocategoria: 'Lavori/Manutenzione',
    importoLordo: 500.00,
    iva: 0.22,
    certezza: 'Certa',
    probabilita: 1.0,
    stato: 'Da pagare',
    fonteContratto: 'Contratto manutenzione',
    ricorrenza: 'Annuale',
  },
];
