import type { PrevisioneEntrata } from './types';

export const previsioniEntrateData: PrevisioneEntrata[] = [
  // LNC Data
  {
    id: 'LNC-PE-1',
    societa: 'LNC',
    anno: 2025,
    mese: 'Luglio',
    dataPrevista: '2025-07-15',
    descrizione: 'Affitto Eris - Luglio',
    categoria: 'Immobiliare',
    sottocategoria: 'Affitti',
    importoLordo: 2008.80,
    iva: 0.22,
    certezza: 'Certa',
    probabilita: 1.0,
    stato: 'Da incassare',
    note: 'Fattura 7/25',
  },
  {
    id: 'LNC-PE-2',
    societa: 'LNC',
    anno: 2025,
    mese: 'Agosto',
    dataPrevista: '2025-08-15',
    descrizione: 'Affitto Eris - Agosto',
    categoria: 'Immobiliare',
    sottocategoria: 'Affitti',
    importoLordo: 2008.80,
    iva: 0.22,
    certezza: 'Certa',
    probabilita: 1.0,
    stato: 'Da incassare',
    note: 'Fattura 8/25',
  },
  {
    id: 'LNC-PE-3',
    societa: 'LNC',
    anno: 2025,
    mese: 'Settembre',
    dataPrevista: '2025-09-15',
    descrizione: 'Affitto Eris - Settembre',
    categoria: 'Immobiliare',
    sottocategoria: 'Affitti',
    importoLordo: 2008.80,
    iva: 0.22,
    certezza: 'Certa',
    probabilita: 1.0,
    stato: 'Incassato',
    note: 'Fattura 9/25 - Incassato in anticipo',
  },
   {
    id: 'LNC-PE-4',
    societa: 'LNC',
    anno: 2025,
    mese: 'Ottobre',
    dataPrevista: '2025-10-20',
    descrizione: 'Vendita Terreno B.Zacco',
    categoria: 'Immobiliare',
    sottocategoria: 'Immobili',
    importoLordo: 50000.00,
    iva: 0.0,
    certezza: 'Probabile',
    probabilita: 0.75,
    stato: 'Da incassare',
    note: 'In attesa di proposta definitiva',
  },

  // STG Data
  {
    id: 'STG-PE-1',
    societa: 'STG',
    anno: 2025,
    mese: 'Luglio',
    dataPrevista: '2025-07-10',
    descrizione: 'Incentivi GSE - Giugno',
    categoria: 'Energia',
    sottocategoria: 'Incentivi GSE',
    importoLordo: 1500.00,
    iva: 0.10,
    certezza: 'Certa',
    probabilita: 1.0,
    stato: 'Incassato',
  },
  {
    id: 'STG-PE-2',
    societa: 'STG',
    anno: 2025,
    mese: 'Luglio',
    dataPrevista: '2025-07-25',
    descrizione: 'Vendita Energia - Giugno',
    categoria: 'Energia',
    sottocategoria: 'Vendita Energia',
    importoLordo: 3200.00,
    iva: 0.10,
    certezza: 'Certa',
    probabilita: 1.0,
    stato: 'Da incassare',
  },
   {
    id: 'STG-PE-3',
    societa: 'STG',
    anno: 2025,
    mese: 'Agosto',
    dataPrevista: '2025-08-10',
    descrizione: 'Incentivi GSE - Luglio',
    categoria: 'Energia',
    sottocategoria: 'Incentivi GSE',
    importoLordo: 1650.00,
    iva: 0.10,
    certezza: 'Probabile',
    probabilita: 0.9,
    stato: 'Da incassare',
  },
  {
    id: 'STG-PE-4',
    societa: 'STG',
    anno: 2025,
    mese: 'Settembre',
    dataPrevista: '2025-09-05',
    descrizione: 'Affitto H&S',
    categoria: 'Immobiliare',
    sottocategoria: 'Affitti',
    importoLordo: 793.00,
    iva: 0.22,
    certezza: 'Certa',
    probabilita: 1.0,
    stato: 'Da incassare',
  },
];
