import type { Scadenza } from './types';

export const scadenzeData: Scadenza[] = [
  {
    id: '1',
    societa: 'LNC',
    anno: 2025,
    dataScadenza: '2025-03-16',
    descrizione: '1° Trimestre 2025',
    categoria: 'IVA Trimestrale',
    importoPrevisto: 1093.00,
    importoPagato: 1093.00,
    stato: 'Pagato',
    ricorrenza: 'Trimestrale',
    note: ''
  },
  {
    id: '2',
    societa: 'LNC',
    anno: 2025,
    dataScadenza: '2025-05-16',
    descrizione: 'IVA 2° Trimestre 2025',
    categoria: 'IVA Trimestrale',
    importoPrevisto: 1093.00,
    importoPagato: 1093.00,
    stato: 'Pagato',
    ricorrenza: 'Trimestrale',
    note: ''
  },
  {
    id: '3',
    societa: 'LNC',
    anno: 2025,
    dataScadenza: '2025-08-20',
    descrizione: 'IVA 3° Trimestre 2025',
    categoria: 'IVA Trimestrale',
    importoPrevisto: 1093.00,
    importoPagato: 1093.00,
    stato: 'Pagato',
    ricorrenza: 'Trimestrale',
    note: ''
  },
  {
    id: '4',
    societa: 'LNC',
    anno: 2025,
    dataScadenza: '2025-11-16',
    descrizione: 'IVA 4° Trimestre 2025',
    categoria: 'IVA Trimestrale',
    importoPrevisto: 1093.00,
    importoPagato: 1093.00,
    stato: 'Pagato',
    ricorrenza: 'Trimestrale',
    note: ''
  },
  {
    id: '5',
    societa: 'LNC',
    anno: 2025,
    dataScadenza: '2025-06-01',
    descrizione: 'IMU 2025 - Acconto',
    categoria: 'IMU',
    importoPrevisto: 460.00,
    importoPagato: 460.00,
    stato: 'Pagato',
    ricorrenza: 'Semestrale',
    note: ''
  },
  {
    id: '6',
    societa: 'LNC',
    anno: 2025,
    dataScadenza: '2025-12-01',
    descrizione: 'IMU 2025 - Saldo',
    categoria: 'IMU',
    importoPrevisto: 460.00,
    importoPagato: 0,
    stato: 'Da pagare',
    ricorrenza: 'Semestrale',
    note: ''
  },
  {
    id: '7',
    societa: 'LNC',
    anno: 2026,
    dataScadenza: '2026-01-05',
    descrizione: 'Accertamento IRPEF Gibilisco Nuccio - Rata 1/5',
    categoria: 'Cartelle Esattoriali',
    importoPrevisto: 1132.96,
    importoPagato: 0,
    stato: 'Da pagare',
    ricorrenza: 'Trimestrale',
    note: 'Rateizzazione 2024'
  },
  {
    id: '8',
    societa: 'LNC',
    anno: 2026,
    dataScadenza: '2026-04-30',
    descrizione: 'Accertamento IRPEF Gibilisco Nuccio - Rata 2/5',
    categoria: 'Cartelle Esattoriali',
    importoPrevisto: 1132.96,
    importoPagato: 0,
    stato: 'Da pagare',
    ricorrenza: 'Trimestrale',
    note: 'Rateizzazione 2024'
  },
  {
    id: '9',
    societa: 'LNC',
    anno: 2026,
    dataScadenza: '2026-07-31',
    descrizione: 'Accertamento IRPEF Gibilisco Nuccio - Rata 3/5',
    categoria: 'Cartelle Esattoriali',
    importoPrevisto: 1132.96,
    importoPagato: 0,
    stato: 'Da pagare',
    ricorrenza: 'Trimestrale',
    note: 'Rateizzazione 2024'
  },
  {
    id: '10',
    societa: 'LNC',
    anno: 2026,
    dataScadenza: '2026-11-02',
    descrizione: 'Accertamento IRPEF Gibilisco Nuccio - Rata 4/5',
    categoria: 'Cartelle Esattoriali',
    importoPrevisto: 1132.96,
    importoPagato: 0,
    stato: 'Da pagare',
    ricorrenza: 'Trimestrale',
    note: 'Rateizzazione 2024'
  },
  {
    id: '11',
    societa: 'LNC',
    anno: 2027,
    dataScadenza: '2027-02-01',
    descrizione: 'Accertamento IRPEF Gibilisco Nuccio - Rata 5/5',
    categoria: 'Cartelle Esattoriali',
    importoPrevisto: 1132.96,
    importoPagato: 0,
    stato: 'Da pagare',
    ricorrenza: 'Trimestrale',
    note: 'Rateizzazione 2024'
  }
];
